### ISSUE TITLE
Can't run example code as shown on npm page.

### ISSUE THREAD

**Issue by DuncanMarshall** [goldfire/pokersolver#5]
I'm running on Ubuntu.

I'm installing pokersolver like so, while in the directory of my project:

    npm install pokersolver

I'm trying to run a file where this is the only line:

    var Hand = require('pokersolve').Hand;

This causes a "Can't find module 'pokersolve'" error.  I figure it's a type so I've changed it to:

   var Hand = require('pokersolver').Hand;

Which causes the following error
```
/media/E/Storage/Code/project/node_modules/pokersolver/pokersolver.js:16
  class Card {
  ^^^^^

SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/media/E/Storage/Code/flopzilla/new_zilla.js:1:74)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

```

**Comment by goldfire** [comment]
Thanks, that typo has been fixed. ES6 classes are only supported in node v4+, and that error looks like you are running on an older version.
